import type { DemoClaim } from "@/lib/types";

// ═══════════════════════════════════════════════════════════════
// DEMO 1 — Hyundai Creta (Fast Track)
// Minor parking scrape, network garage, low settlement, low risk
// ═══════════════════════════════════════════════════════════════
const cretaClaim: DemoClaim = {
  claimId: "CLM-CRETA-001",
  label: "Hyundai Creta — Parking Scrape",
  purpose: "Demonstrate Fast Track",
  expectedRoute: "Fast Track",
  estimateImage: "/demo/creta-estimate.png",
  aiMode: "DEMO",
  context: {
    policySchedule: {
      policyNumber: "AD26COMP01458",
      policyCode: "AD-COMP-01",
      policyStartDate: "2026-04-01",
      policyEndDate: "2027-03-31",
      idv: 1200000,
      compulsoryDeductible: 1000,
      voluntaryDeductible: 0,
      activeAddOns: [],
      odClaimsThisPolicyYear: 0,
    },
    claim: {
      claimNumber: "CLM-CRETA-001",
      policyNumber: "AD26COMP01458",
      lossDate: "2026-08-20",
      accidentDescription: "Minor scrape against a parking pillar while reversing.",
      primaryImpactLocation: "left-front bumper corner",
      injuryInvolved: false,
      thirdPartyInvolved: false,
      policeReportRequired: false,
    },
    vehicle: {
      registration: "TS09AB4582",
      make: "Hyundai",
      model: "Creta",
      variant: "1.5 SX",
      modelYear: 2024,
      engineCC: 1497,
      vehicleAgeYears: 2.0,
      odometerKm: 18420,
    },
    garage: {
      name: "Prime Wheels Body & Paint",
      city: "Hyderabad",
      networkStatus: "network",
    },
    documentsAvailable: {
      workshopEstimate: true,
      accidentNarrative: true,
      vehicleRegistration: true,
      policyConfirmation: true,
      drivingLicence: true,
      damagePhotographs: true,
    },
  },
  structuredClaim: {
    claim: {
      claimNumber: "CLM-CRETA-001",
      lossDate: "2026-08-20",
      accidentDescription: "Minor scrape against a parking pillar while reversing.",
      primaryImpactLocation: "left-front bumper corner",
    },
    vehicle: {
      registration: "TS09AB4582",
      make: "Hyundai",
      model: "Creta",
      variant: "1.5 SX",
      modelYear: 2024,
      engineCC: 1497,
      vehicleAgeYears: 2.0,
    },
    garage: {
      name: "Prime Wheels Body & Paint",
      city: "Hyderabad",
      networkStatus: "network",
    },
    estimate: {
      estimateNumber: "PW-2026-0820",
      partsTotal: 6500,
      labourTotal: 1800,
      paintTotal: 3800,
      grandTotal: 12100,
    },
    lineItems: [
      {
        id: "L1",
        rawDescription: "Fr bumper assy — replacement",
        normalizedDescription: "Front bumper assembly — replacement",
        quantity: 1,
        partCost: 4000,
        labourCost: 1000,
        totalCost: 5000,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T1-R2-C1", "P1-T1-R2-C3"],
        confidence: "high",
      },
      {
        id: "L2",
        rawDescription: "Fr bumper painting",
        normalizedDescription: "Front bumper painting",
        quantity: 1,
        paintCost: 2000,
        totalCost: 2000,
        category: "paint",
        material: "paint",
        action: "paint",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T1-R3-C1"],
        confidence: "high",
      },
      {
        id: "L3",
        rawDescription: "LH fender — dent repair",
        normalizedDescription: "Left front fender — dent repair",
        quantity: 1,
        partCost: 2500,
        labourCost: 800,
        paintCost: 1800,
        totalCost: 5100,
        category: "part",
        material: "metal",
        action: "repair",
        vehicleLocation: "left front fender",
        sourceBlockIds: ["P1-T1-R4-C1", "P1-T1-R4-C2"],
        confidence: "high",
      },
    ],
    missingInformation: [],
  },
  semanticReview: [
    { itemId: "L1", normalizedDescription: "Front bumper assembly — replacement", classification: "CONSISTENT", reason: "Front bumper damage is consistent with a left-front parking scrape." },
    { itemId: "L2", normalizedDescription: "Front bumper painting", classification: "CONSISTENT", reason: "Painting follows bumper replacement." },
    { itemId: "L3", normalizedDescription: "Left front fender — dent repair", classification: "CONSISTENT", reason: "Left-front fender damage is consistent with the stated left-front impact location." },
  ],
};

// ═══════════════════════════════════════════════════════════════
// DEMO 2 — Honda City (Desktop Review)
// Front-right collision, moderate settlement, repair/replace ambiguity
// ═══════════════════════════════════════════════════════════════
const hondaCityClaim: DemoClaim = {
  claimId: "CLM-HCITY-002",
  label: "Honda City — Front-Right Collision",
  purpose: "Demonstrate Desktop Review",
  expectedRoute: "Desktop Review",
  estimateImage: "/demo/honda-city-estimate.png",
  aiMode: "DEMO",
  context: {
    policySchedule: {
      policyNumber: "AD26COMP07713",
      policyCode: "AD-COMP-01",
      policyStartDate: "2026-05-01",
      policyEndDate: "2027-04-30",
      idv: 780000,
      compulsoryDeductible: 1000,
      voluntaryDeductible: 0,
      activeAddOns: [],
      odClaimsThisPolicyYear: 0,
    },
    claim: {
      claimNumber: "CLM-HCITY-002",
      policyNumber: "AD26COMP07713",
      lossDate: "2026-08-21",
      accidentDescription: "Vehicle struck another vehicle at the front-right corner at moderate speed.",
      primaryImpactLocation: "front-right bumper / headlamp / fender",
      injuryInvolved: false,
      thirdPartyInvolved: true,
      policeReportRequired: false,
    },
    vehicle: {
      registration: "MH12QK7713",
      make: "Honda",
      model: "City",
      variant: "VX CVT",
      modelYear: 2022,
      engineCC: 1498,
      vehicleAgeYears: 4.0,
      odometerKm: 42650,
    },
    garage: {
      name: "CityDrive Auto Care",
      city: "Pune",
      networkStatus: "network",
    },
    documentsAvailable: {
      workshopEstimate: true,
      accidentNarrative: true,
      vehicleRegistration: true,
      policyConfirmation: true,
      drivingLicence: true,
      damagePhotographs: true,
    },
  },
  structuredClaim: {
    claim: {
      claimNumber: "CLM-HCITY-002",
      lossDate: "2026-08-21",
      accidentDescription: "Vehicle struck another vehicle at the front-right corner at moderate speed.",
      primaryImpactLocation: "front-right bumper / headlamp / fender",
    },
    vehicle: {
      registration: "MH12QK7713",
      make: "Honda",
      model: "City",
      variant: "VX CVT",
      modelYear: 2022,
      engineCC: 1498,
      vehicleAgeYears: 4.0,
    },
    garage: {
      name: "CityDrive Auto Care",
      city: "Pune",
      networkStatus: "network",
    },
    estimate: {
      estimateNumber: "CDA-2026-0821",
      partsTotal: 84000,
      labourTotal: 19500,
      paintTotal: 18000,
      grandTotal: 121500,
    },
    lineItems: [
      {
        id: "L1",
        rawDescription: "Fr bumper cover — replacement",
        normalizedDescription: "Front bumper cover — replacement",
        quantity: 1,
        partCost: 18000,
        labourCost: 4000,
        totalCost: 22000,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T2-R2-C1", "P1-T2-R2-C3"],
        confidence: "high",
      },
      {
        id: "L2",
        rawDescription: "Fr bumper painting",
        normalizedDescription: "Front bumper painting",
        quantity: 1,
        paintCost: 6000,
        totalCost: 6000,
        category: "paint",
        material: "paint",
        action: "paint",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T2-R3-C1"],
        confidence: "high",
      },
      {
        id: "L3",
        rawDescription: "FR RH headlamp assy — replacement",
        normalizedDescription: "Front right headlamp assembly — replacement",
        quantity: 1,
        partCost: 28000,
        labourCost: 2000,
        totalCost: 30000,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front right",
        sourceBlockIds: ["P1-T2-R4-C1", "P1-T2-R4-C3"],
        confidence: "high",
      },
      {
        id: "L4",
        rawDescription: "FR RH fender — replacement",
        normalizedDescription: "Front right fender — replacement",
        quantity: 1,
        partCost: 12000,
        labourCost: 3000,
        paintCost: 5000,
        totalCost: 20000,
        category: "part",
        material: "metal",
        action: "replace",
        vehicleLocation: "front right fender",
        sourceBlockIds: ["P1-T2-R5-C1", "P1-T2-R5-C2"],
        confidence: "medium",
      },
      {
        id: "L5",
        rawDescription: "Fr grille — replacement",
        normalizedDescription: "Front grille — replacement",
        quantity: 1,
        partCost: 6000,
        labourCost: 1500,
        totalCost: 7500,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front grille",
        sourceBlockIds: ["P1-T2-R6-C1"],
        confidence: "high",
      },
      {
        id: "L6",
        rawDescription: "Bonnet — dent repair & paint",
        normalizedDescription: "Bonnet — dent repair and painting",
        quantity: 1,
        partCost: 8000,
        labourCost: 4000,
        paintCost: 7000,
        totalCost: 19000,
        category: "part",
        material: "metal",
        action: "repair",
        vehicleLocation: "bonnet",
        sourceBlockIds: ["P1-T2-R7-C1", "P1-T2-R7-C2"],
        confidence: "medium",
      },
      {
        id: "L7",
        rawDescription: "Radiator support — replacement",
        normalizedDescription: "Radiator support — replacement",
        quantity: 1,
        partCost: 7000,
        labourCost: 3000,
        totalCost: 10000,
        category: "part",
        material: "metal",
        action: "replace",
        vehicleLocation: "front",
        sourceBlockIds: ["P1-T2-R8-C1"],
        confidence: "high",
      },
      {
        id: "L8",
        rawDescription: "Fr bumper beam — replacement",
        normalizedDescription: "Front bumper beam — replacement",
        quantity: 1,
        partCost: 5000,
        labourCost: 2000,
        totalCost: 7000,
        category: "part",
        material: "metal",
        action: "replace",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T2-R9-C1"],
        confidence: "high",
      },
    ],
    missingInformation: [],
  },
  semanticReview: [
    { itemId: "L1", normalizedDescription: "Front bumper cover — replacement", classification: "CONSISTENT", reason: "Front bumper damage is consistent with front-right collision." },
    { itemId: "L2", normalizedDescription: "Front bumper painting", classification: "CONSISTENT", reason: "Painting follows bumper replacement." },
    { itemId: "L3", normalizedDescription: "Front right headlamp assembly — replacement", classification: "CONSISTENT", reason: "Front-right headlamp damage is consistent with the stated front-right impact." },
    { itemId: "L4", normalizedDescription: "Front right fender — replacement", classification: "POSSIBLY_CONSISTENT", reason: "Fender replacement is plausible for a front-right collision, but repair may have been sufficient — verify repair vs replace basis." },
    { itemId: "L5", normalizedDescription: "Front grille — replacement", classification: "CONSISTENT", reason: "Grille damage is consistent with front impact." },
    { itemId: "L6", normalizedDescription: "Bonnet — dent repair and painting", classification: "POSSIBLY_CONSISTENT", reason: "Bonnet damage is possible in a moderate-speed front collision, but should be verified against damage photographs." },
    { itemId: "L7", normalizedDescription: "Radiator support — replacement", classification: "CONSISTENT", reason: "Radiator support damage is consistent with front-end collision." },
    { itemId: "L8", normalizedDescription: "Front bumper beam — replacement", classification: "CONSISTENT", reason: "Bumper beam damage is consistent with front impact." },
  ],
};

// ═══════════════════════════════════════════════════════════════
// DEMO 3 — BMW 3-Series (Specialist Review)
// Premium non-network, high labour, duplicate, impact mismatch, high value
// ═══════════════════════════════════════════════════════════════
const bmwClaim: DemoClaim = {
  claimId: "CLM-BMW-003",
  label: "BMW 320d — Front Collision (Premium Non-Network)",
  purpose: "Demonstrate Specialist Review",
  expectedRoute: "Specialist Review",
  estimateImage: "/demo/bmw-estimate.png",
  aiMode: "DEMO",
  context: {
    policySchedule: {
      policyNumber: "AD26ELITE00982",
      policyCode: "AD-ELITE-02",
      policyStartDate: "2026-04-01",
      policyEndDate: "2027-03-31",
      idv: 1200000,
      compulsoryDeductible: 2000,
      voluntaryDeductible: 0,
      activeAddOns: ["ZERO_DEPRECIATION", "CONSUMABLES"],
      odClaimsThisPolicyYear: 1,
      originalInvoiceValue: 4600000,
      benefitUsage: {
        engineProtectUsed: 0,
        tyreProtectUsed: 0,
        keyReplacementUsed: 0,
        rsaEventsUsed: 0,
      },
    },
    claim: {
      claimNumber: "CLM-BMW-003",
      policyNumber: "AD26ELITE00982",
      lossDate: "2026-08-22",
      accidentDescription: "Vehicle collided with a road divider at the front-right corner.",
      primaryImpactLocation: "front-right",
      injuryInvolved: false,
      thirdPartyInvolved: false,
      policeReportRequired: false,
    },
    vehicle: {
      registration: "MH01AB1234",
      make: "BMW",
      model: "320d",
      variant: "Luxury Line",
      modelYear: 2021,
      engineCC: 1995,
      vehicleAgeYears: 4.75,
      odometerKm: 58900,
    },
    garage: {
      name: "Prestige Motor Works",
      city: "Mumbai",
      networkStatus: "non_network",
    },
    documentsAvailable: {
      workshopEstimate: true,
      accidentNarrative: true,
      vehicleRegistration: true,
      policyConfirmation: true,
      drivingLicence: true,
      damagePhotographs: true,
    },
  },
  structuredClaim: {
    claim: {
      claimNumber: "CLM-BMW-003",
      lossDate: "2026-08-22",
      accidentDescription: "Vehicle collided with a road divider at the front-right corner.",
      primaryImpactLocation: "front-right",
    },
    vehicle: {
      registration: "MH01AB1234",
      make: "BMW",
      model: "320d",
      variant: "Luxury Line",
      modelYear: 2021,
      engineCC: 1995,
      vehicleAgeYears: 4.75,
    },
    garage: {
      name: "Prestige Motor Works",
      city: "Mumbai",
      networkStatus: "non_network",
    },
    estimate: {
      estimateNumber: "PMW-2026-0822",
      partsTotal: 310000,
      labourTotal: 49500,
      paintTotal: 41000,
      grandTotal: 408500,
    },
    lineItems: [
      {
        id: "L1",
        rawDescription: "Fr bumper cover — replacement (OEM)",
        normalizedDescription: "Front bumper cover — OEM replacement",
        quantity: 1,
        partCost: 42000,
        labourCost: 7500,
        totalCost: 49500,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T3-R2-C1", "P1-T3-R2-C4"],
        confidence: "high",
      },
      {
        id: "L2",
        rawDescription: "Fr bumper painting",
        normalizedDescription: "Front bumper painting",
        quantity: 1,
        paintCost: 14000,
        totalCost: 14000,
        category: "paint",
        material: "paint",
        action: "paint",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T3-R3-C1"],
        confidence: "high",
      },
      {
        id: "L3",
        rawDescription: "FR RH headlamp LED assy — replacement",
        normalizedDescription: "Front right LED headlamp assembly — replacement",
        quantity: 1,
        partCost: 78000,
        labourCost: 4500,
        totalCost: 82500,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front right",
        sourceBlockIds: ["P1-T3-R4-C1", "P1-T3-R4-C3"],
        confidence: "high",
      },
      {
        id: "L4",
        rawDescription: "FR RH fender — replacement",
        normalizedDescription: "Front right fender — replacement",
        quantity: 1,
        partCost: 35000,
        labourCost: 6000,
        paintCost: 11000,
        totalCost: 52000,
        category: "part",
        material: "metal",
        action: "replace",
        vehicleLocation: "front right fender",
        sourceBlockIds: ["P1-T3-R5-C1", "P1-T3-R5-C2"],
        confidence: "high",
      },
      {
        id: "L5",
        rawDescription: "Fr grille — replacement",
        normalizedDescription: "Front grille — replacement",
        quantity: 1,
        partCost: 14000,
        labourCost: 2000,
        totalCost: 16000,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front grille",
        sourceBlockIds: ["P1-T3-R6-C1"],
        confidence: "high",
      },
      {
        id: "L6",
        rawDescription: "Bonnet — replacement",
        normalizedDescription: "Bonnet — replacement",
        quantity: 1,
        partCost: 52000,
        labourCost: 9000,
        paintCost: 16000,
        totalCost: 77000,
        category: "part",
        material: "metal",
        action: "replace",
        vehicleLocation: "bonnet",
        sourceBlockIds: ["P1-T3-R7-C1", "P1-T3-R7-C2"],
        confidence: "high",
      },
      {
        id: "L7",
        rawDescription: "Radiator — replacement",
        normalizedDescription: "Radiator — replacement",
        quantity: 1,
        partCost: 25000,
        labourCost: 5500,
        totalCost: 30500,
        category: "part",
        material: "metal",
        action: "replace",
        vehicleLocation: "front",
        sourceBlockIds: ["P1-T3-R8-C1"],
        confidence: "high",
      },
      {
        id: "L8",
        rawDescription: "Radiator support — replacement",
        normalizedDescription: "Radiator support — replacement",
        quantity: 1,
        partCost: 16000,
        labourCost: 4500,
        totalCost: 20500,
        category: "part",
        material: "metal",
        action: "replace",
        vehicleLocation: "front",
        sourceBlockIds: ["P1-T3-R9-C1"],
        confidence: "high",
      },
      {
        id: "L9",
        rawDescription: "AC condenser — replacement",
        normalizedDescription: "AC condenser — replacement",
        quantity: 1,
        partCost: 20000,
        labourCost: 4000,
        totalCost: 24000,
        category: "part",
        material: "metal",
        action: "replace",
        vehicleLocation: "front",
        sourceBlockIds: ["P1-T3-R10-C1"],
        confidence: "high",
      },
      {
        id: "L10",
        rawDescription: "Fr bumper D&F labour",
        normalizedDescription: "Front bumper removal and refit labour",
        quantity: 1,
        labourCost: 3500,
        totalCost: 3500,
        category: "labour",
        material: "unknown",
        action: "repair",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T3-R11-C1"],
        confidence: "low",
      },
      {
        id: "L11",
        rawDescription: "RR LH tail lamp — replacement",
        normalizedDescription: "Rear left tail lamp — replacement",
        quantity: 1,
        partCost: 28000,
        labourCost: 3000,
        totalCost: 31000,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "rear left",
        sourceBlockIds: ["P1-T3-R12-C1", "P1-T3-R12-C3"],
        confidence: "low",
      },
      {
        id: "L12",
        rawDescription: "Consumables",
        normalizedDescription: "Consumables (oil, coolant, clips, fasteners)",
        quantity: 1,
        partCost: 8000,
        totalCost: 8000,
        category: "other",
        material: "unknown",
        action: "unknown",
        sourceBlockIds: ["P1-T3-R13-C1"],
        confidence: "high",
      },
    ],
    missingInformation: [],
  },
  semanticReview: [
    { itemId: "L1", normalizedDescription: "Front bumper cover — OEM replacement", classification: "CONSISTENT", reason: "Front bumper damage is consistent with front-right collision." },
    { itemId: "L2", normalizedDescription: "Front bumper painting", classification: "CONSISTENT", reason: "Painting follows bumper replacement." },
    { itemId: "L3", normalizedDescription: "Front right LED headlamp assembly — replacement", classification: "CONSISTENT", reason: "Front-right headlamp damage is consistent with the stated front-right impact." },
    { itemId: "L4", normalizedDescription: "Front right fender — replacement", classification: "CONSISTENT", reason: "Front-right fender damage is consistent with front-right impact." },
    { itemId: "L5", normalizedDescription: "Front grille — replacement", classification: "CONSISTENT", reason: "Grille damage is consistent with front impact." },
    { itemId: "L6", normalizedDescription: "Bonnet — replacement", classification: "CONSISTENT", reason: "Bonnet damage is consistent with front collision with a divider." },
    { itemId: "L7", normalizedDescription: "Radiator — replacement", classification: "CONSISTENT", reason: "Radiator damage is consistent with front-end collision." },
    { itemId: "L8", normalizedDescription: "Radiator support — replacement", classification: "CONSISTENT", reason: "Radiator support damage is consistent with front impact." },
    { itemId: "L9", normalizedDescription: "AC condenser — replacement", classification: "CONSISTENT", reason: "AC condenser damage is consistent with front-end collision." },
    { itemId: "L10", normalizedDescription: "Front bumper removal and refit labour", classification: "INCONSISTENT_WITH_DESCRIPTION", reason: "Duplicate labour operation — bumper removal labour is already included in the bumper replacement line item (L1). This appears to be a duplicate charge." },
    { itemId: "L11", normalizedDescription: "Rear left tail lamp — replacement", classification: "INCONSISTENT_WITH_DESCRIPTION", reason: "Rear-left tail lamp replacement does not correspond with the documented front-right impact. This repair location is inconsistent with the stated primary impact area." },
    { itemId: "L12", normalizedDescription: "Consumables (oil, coolant, clips, fasteners)", classification: "CONSISTENT", reason: "Consumables are standard for a major front-end repair." },
  ],
};

export const demoClaims: DemoClaim[] = [cretaClaim, hondaCityClaim, bmwClaim];

export function getDemoClaim(claimId: string): DemoClaim | undefined {
  return demoClaims.find((c) => c.claimId === claimId);
}
