import type { DemoClaim } from "@/lib/types";

// ═══════════════════════════════════════════════════════════════
// DEMO 1 — Hyundai Creta (Fast Track)
// Minor parking scrape, network garage, low settlement, low risk
// ═══════════════════════════════════════════════════════════════
const cretaClaim: DemoClaim = {
  claimId: "CLM-CRETA-001",
  label: "Hyundai Creta — Parking Scrape",
  purpose: "Demonstrate Fast Track",
  expectedRoute: "Fast Track",
  estimateImage: "/demo/creta-estimate.png",
  aiMode: "DEMO",
  context: {
    policySchedule: {
      policyNumber: "AD26COMP01458",
      policyCode: "AD-COMP-01",
      policyStartDate: "2026-04-01",
      policyEndDate: "2027-03-31",
      idv: 1200000,
      compulsoryDeductible: 1000,
      voluntaryDeductible: 0,
      activeAddOns: [],
      odClaimsThisPolicyYear: 0,
    },
    claim: {
      claimNumber: "CLM-CRETA-001",
      policyNumber: "AD26COMP01458",
      lossDate: "2026-08-20",
      accidentDescription: "Minor scrape against a parking pillar while reversing.",
      primaryImpactLocation: "left-front bumper corner",
      injuryInvolved: false,
      thirdPartyInvolved: false,
      policeReportRequired: false,
    },
    vehicle: {
      registration: "TS09AB4582",
      make: "Hyundai",
      model: "Creta",
      variant: "1.5 SX",
      modelYear: 2024,
      engineCC: 1497,
      vehicleAgeYears: 2.0,
      odometerKm: 18420,
    },
    garage: {
      name: "Prime Wheels Body & Paint",
      city: "Hyderabad",
      networkStatus: "network",
    },
    documentsAvailable: {
      workshopEstimate: true,
      accidentNarrative: true,
      vehicleRegistration: true,
      policyConfirmation: true,
      drivingLicence: true,
      damagePhotographs: true,
    },
  },
  structuredClaim: {
    claim: {
      claimNumber: "CLM-CRETA-001",
      lossDate: "2026-08-20",
      accidentDescription: "Minor scrape against a parking pillar while reversing.",
      primaryImpactLocation: "left-front bumper corner",
    },
    vehicle: {
      registration: "TS09AB4582",
      make: "Hyundai",
      model: "Creta",
      variant: "1.5 SX",
      modelYear: 2024,
      engineCC: 1497,
      vehicleAgeYears: 2.0,
    },
    garage: {
      name: "Prime Wheels Body & Paint",
      city: "Hyderabad",
      networkStatus: "network",
    },
    estimate: {
      estimateNumber: "PWB-EST-260821-014",
      partsTotal: 25200,
      labourTotal: 6400,
      paintTotal: 3200,
      grandTotal: 41064,
    },
    lineItems: [
      {
        id: "L1",
        rawDescription: "Front bumper assembly",
        normalizedDescription: "Front bumper assembly",
        quantity: 1,
        partCost: 18500,
        labourCost: 1800,
        totalCost: 20300,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T1-R2-C1", "P1-T1-R2-C3"],
        confidence: "high",
      },
      {
        id: "L2",
        rawDescription: "Front bumper painting",
        normalizedDescription: "Front bumper painting",
        quantity: 1,
        labourCost: 1200,
        paintCost: 3200,
        totalCost: 4400,
        category: "paint",
        material: "paint",
        action: "paint",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T1-R3-C1"],
        confidence: "high",
      },
      {
        id: "L3",
        rawDescription: "LH bumper garnish",
        normalizedDescription: "Left-hand bumper garnish",
        quantity: 1,
        partCost: 2950,
        labourCost: 450,
        totalCost: 3400,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "left front bumper",
        sourceBlockIds: ["P1-T1-R4-C1", "P1-T1-R4-C2"],
        confidence: "high",
      },
      {
        id: "L4",
        rawDescription: "Bumper clips & retainers set",
        normalizedDescription: "Bumper clips and retainers set",
        quantity: 1,
        partCost: 850,
        labourCost: 250,
        totalCost: 1100,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T1-R5-C1"],
        confidence: "high",
      },
      {
        id: "L5",
        rawDescription: "LH fog lamp bezel",
        normalizedDescription: "Left-hand fog lamp bezel",
        quantity: 1,
        partCost: 1650,
        labourCost: 350,
        totalCost: 2000,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "left front bumper",
        sourceBlockIds: ["P1-T1-R6-C1"],
        confidence: "high",
      },
      {
        id: "L6",
        rawDescription: "Underbody splash shield repair",
        normalizedDescription: "Underbody splash shield repair",
        quantity: 1,
        labourCost: 1600,
        totalCost: 1600,
        category: "labour",
        material: "plastic",
        action: "repair",
        vehicleLocation: "left front underbody",
        sourceBlockIds: ["P1-T1-R7-C1"],
        confidence: "high",
      },
      {
        id: "L7",
        rawDescription: "Detailing & polish",
        normalizedDescription: "Detailing and polish",
        quantity: 1,
        labourCost: 750,
        totalCost: 750,
        category: "labour",
        material: "unknown",
        action: "repair",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T1-R8-C1"],
        confidence: "high",
      },
      {
        id: "L8",
        rawDescription: "Consumables / masking materials",
        normalizedDescription: "Consumables and masking materials",
        quantity: 1,
        partCost: 1250,
        totalCost: 1250,
        category: "other",
        material: "unknown",
        action: "unknown",
        sourceBlockIds: ["P1-T1-R9-C1"],
        confidence: "high",
      },
      {
        id: "L9",
        rawDescription: "Tax @18%",
        normalizedDescription: "GST at 18%",
        quantity: 1,
        totalCost: 6264,
        category: "other",
        material: "unknown",
        action: "unknown",
        sourceBlockIds: ["P1-SUMMARY-TAX"],
        confidence: "high",
      },
    ],
    missingInformation: [],
  },
  semanticReview: [
    { itemId: "L1", normalizedDescription: "Front bumper assembly", classification: "CONSISTENT", reason: "Front bumper damage is consistent with a left-front parking scrape." },
    { itemId: "L2", normalizedDescription: "Front bumper painting", classification: "CONSISTENT", reason: "Painting follows bumper replacement." },
    { itemId: "L3", normalizedDescription: "Left-hand bumper garnish", classification: "CONSISTENT", reason: "The left bumper garnish is at the stated impact location." },
    { itemId: "L4", normalizedDescription: "Bumper clips and retainers set", classification: "CONSISTENT", reason: "Clips and retainers are plausible supporting parts for bumper replacement." },
    { itemId: "L5", normalizedDescription: "Left-hand fog lamp bezel", classification: "CONSISTENT", reason: "The left fog-lamp bezel is at the stated impact location." },
    { itemId: "L6", normalizedDescription: "Underbody splash shield repair", classification: "CONSISTENT", reason: "The left-front underbody shield is adjacent to the stated impact." },
    { itemId: "L7", normalizedDescription: "Detailing and polish", classification: "CONSISTENT", reason: "Finishing work is plausible after a bumper repair." },
    { itemId: "L8", normalizedDescription: "Consumables and masking materials", classification: "CONSISTENT", reason: "Consumables are plausible for body and paint work." },
    { itemId: "L9", normalizedDescription: "GST at 18%", classification: "CONSISTENT", reason: "The tax line reconciles the estimate subtotal to the stated grand total." },
  ],
};

// ═══════════════════════════════════════════════════════════════
// DEMO 2 — Honda City (Desktop Review)
// Front-right collision, moderate settlement, repair/replace ambiguity
// ═══════════════════════════════════════════════════════════════
const hondaCityClaim: DemoClaim = {
  claimId: "CLM-HCITY-002",
  label: "Honda City — Front-Right Collision",
  purpose: "Demonstrate Desktop Review",
  expectedRoute: "Desktop Review",
  estimateImage: "/demo/honda-city-estimate.png",
  aiMode: "DEMO",
  context: {
    policySchedule: {
      policyNumber: "AD26COMP07713",
      policyCode: "AD-COMP-01",
      policyStartDate: "2026-05-01",
      policyEndDate: "2027-04-30",
      idv: 780000,
      compulsoryDeductible: 1000,
      voluntaryDeductible: 0,
      activeAddOns: [],
      odClaimsThisPolicyYear: 0,
    },
    claim: {
      claimNumber: "CLM-HCITY-002",
      policyNumber: "AD26COMP07713",
      lossDate: "2026-08-21",
      accidentDescription: "Vehicle struck another vehicle at the front-right corner at moderate speed.",
      primaryImpactLocation: "front-right bumper / headlamp / fender",
      injuryInvolved: false,
      thirdPartyInvolved: true,
      policeReportRequired: false,
    },
    vehicle: {
      registration: "MH12QK7713",
      make: "Honda",
      model: "City",
      variant: "VX CVT",
      modelYear: 2022,
      engineCC: 1498,
      vehicleAgeYears: 4.0,
      odometerKm: 42650,
    },
    garage: {
      name: "CityDrive Auto Care",
      city: "Pune",
      networkStatus: "network",
    },
    documentsAvailable: {
      workshopEstimate: true,
      accidentNarrative: true,
      vehicleRegistration: true,
      policyConfirmation: true,
      drivingLicence: true,
      damagePhotographs: true,
    },
  },
  structuredClaim: {
    claim: {
      claimNumber: "CLM-HCITY-002",
      lossDate: "2026-08-21",
      accidentDescription: "Vehicle struck another vehicle at the front-right corner at moderate speed.",
      primaryImpactLocation: "front-right bumper / headlamp / fender",
    },
    vehicle: {
      registration: "MH12QK7713",
      make: "Honda",
      model: "City",
      variant: "VX CVT",
      modelYear: 2022,
      engineCC: 1498,
      vehicleAgeYears: 4.0,
    },
    garage: {
      name: "CityDrive Auto Care",
      city: "Pune",
      networkStatus: "network",
    },
    estimate: {
      estimateNumber: "CDA-EST-260821-037",
      partsTotal: 83300,
      labourTotal: 12800,
      paintTotal: 8700,
      grandTotal: 123664,
    },
    lineItems: [
      {
        id: "L1",
        rawDescription: "Front bumper assembly",
        normalizedDescription: "Front bumper assembly",
        quantity: 1,
        partCost: 22000,
        labourCost: 2000,
        totalCost: 24000,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T2-R2-C1", "P1-T2-R2-C3"],
        confidence: "high",
      },
      {
        id: "L2",
        rawDescription: "RH headlamp assembly",
        normalizedDescription: "Right-hand headlamp assembly",
        quantity: 1,
        partCost: 31500,
        labourCost: 1800,
        totalCost: 33300,
        category: "part",
        material: "electrical",
        action: "replace",
        vehicleLocation: "front right",
        sourceBlockIds: ["P1-T2-R3-C1"],
        confidence: "high",
      },
      {
        id: "L3",
        rawDescription: "RH front fender",
        normalizedDescription: "Right-hand front fender",
        quantity: 1,
        partCost: 12800,
        labourCost: 2400,
        paintCost: 4500,
        totalCost: 19700,
        category: "part",
        material: "metal",
        action: "replace",
        vehicleLocation: "front right fender",
        sourceBlockIds: ["P1-T2-R4-C1", "P1-T2-R4-C3"],
        confidence: "high",
      },
      {
        id: "L4",
        rawDescription: "Front bumper reinforcement",
        normalizedDescription: "Front bumper reinforcement",
        quantity: 1,
        partCost: 7600,
        labourCost: 1000,
        totalCost: 8600,
        category: "part",
        material: "metal",
        action: "replace",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T2-R5-C1", "P1-T2-R5-C2"],
        confidence: "medium",
      },
      {
        id: "L5",
        rawDescription: "RH wheel arch liner",
        normalizedDescription: "Right-hand wheel arch liner",
        quantity: 1,
        partCost: 2200,
        labourCost: 600,
        totalCost: 2800,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front right wheel arch",
        sourceBlockIds: ["P1-T2-R6-C1"],
        confidence: "high",
      },
      {
        id: "L6",
        rawDescription: "Front grille",
        normalizedDescription: "Front grille",
        quantity: 1,
        partCost: 5400,
        labourCost: 500,
        totalCost: 5900,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front grille",
        sourceBlockIds: ["P1-T2-R7-C1", "P1-T2-R7-C2"],
        confidence: "medium",
      },
      {
        id: "L7",
        rawDescription: "Front bumper painting",
        normalizedDescription: "Front bumper painting",
        quantity: 1,
        labourCost: 1500,
        paintCost: 4200,
        totalCost: 5700,
        category: "paint",
        material: "paint",
        action: "paint",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T2-R8-C1"],
        confidence: "high",
      },
      {
        id: "L8",
        rawDescription: "Wheel alignment",
        normalizedDescription: "Wheel alignment",
        quantity: 1,
        labourCost: 1200,
        totalCost: 1200,
        category: "labour",
        material: "mechanical",
        action: "inspect",
        vehicleLocation: "front axle",
        sourceBlockIds: ["P1-T2-R9-C1"],
        confidence: "high",
      },
      {
        id: "L9",
        rawDescription: "A/C condenser bracket straightening",
        normalizedDescription: "Air-conditioning condenser bracket straightening",
        quantity: 1,
        labourCost: 1800,
        totalCost: 1800,
        category: "labour",
        material: "metal",
        action: "repair",
        vehicleLocation: "front right",
        sourceBlockIds: ["P1-T2-R10-C1"],
        confidence: "medium",
      },
      {
        id: "L10",
        rawDescription: "Consumables / sealant kit",
        normalizedDescription: "Consumables and sealant kit",
        quantity: 1,
        partCost: 1800,
        totalCost: 1800,
        category: "other",
        material: "unknown",
        action: "unknown",
        sourceBlockIds: ["P1-T2-R11-C1"],
        confidence: "high",
      },
      {
        id: "L11",
        rawDescription: "Tax @18%",
        normalizedDescription: "GST at 18%",
        quantity: 1,
        totalCost: 18864,
        category: "other",
        material: "unknown",
        action: "unknown",
        sourceBlockIds: ["P1-SUMMARY-TAX"],
        confidence: "high",
      },
    ],
    missingInformation: [],
  },
  semanticReview: [
    { itemId: "L1", normalizedDescription: "Front bumper assembly", classification: "CONSISTENT", reason: "Front bumper damage is consistent with the documented front-right collision." },
    { itemId: "L2", normalizedDescription: "Right-hand headlamp assembly", classification: "CONSISTENT", reason: "The right headlamp is at the stated impact location." },
    { itemId: "L3", normalizedDescription: "Right-hand front fender", classification: "POSSIBLY_CONSISTENT", reason: "Fender replacement is plausible, but the estimate notes that repairability should be confirmed after dismantling." },
    { itemId: "L4", normalizedDescription: "Front bumper reinforcement", classification: "CONSISTENT", reason: "The bumper reinforcement is consistent with a moderate front impact." },
    { itemId: "L5", normalizedDescription: "Right-hand wheel arch liner", classification: "CONSISTENT", reason: "The right wheel-arch liner is adjacent to the stated impact." },
    { itemId: "L6", normalizedDescription: "Front grille", classification: "CONSISTENT", reason: "The grille is within the front impact zone." },
    { itemId: "L7", normalizedDescription: "Front bumper painting", classification: "CONSISTENT", reason: "Painting follows bumper replacement." },
    { itemId: "L8", normalizedDescription: "Wheel alignment", classification: "POSSIBLY_CONSISTENT", reason: "Alignment is plausible after a front-corner impact and should be confirmed by inspection." },
    { itemId: "L9", normalizedDescription: "Air-conditioning condenser bracket straightening", classification: "POSSIBLY_CONSISTENT", reason: "Bracket damage is plausible but requires dismantling evidence." },
    { itemId: "L10", normalizedDescription: "Consumables and sealant kit", classification: "CONSISTENT", reason: "Consumables are plausible for the quoted repair operations." },
    { itemId: "L11", normalizedDescription: "GST at 18%", classification: "CONSISTENT", reason: "The tax line reconciles the estimate subtotal to the stated grand total." },
  ],
};

// ═══════════════════════════════════════════════════════════════
// DEMO 3 — BMW 3-Series (Specialist Review)
// Premium non-network, high labour, duplicate, impact mismatch, high value
// ═══════════════════════════════════════════════════════════════
const bmwClaim: DemoClaim = {
  claimId: "CLM-BMW-003",
  label: "BMW 320d — Front Collision (Premium Non-Network)",
  purpose: "Demonstrate Specialist Review",
  expectedRoute: "Specialist Review",
  estimateImage: "/demo/bmw-estimate.png",
  aiMode: "DEMO",
  context: {
    policySchedule: {
      policyNumber: "AD26ELITE00982",
      policyCode: "AD-ELITE-02",
      policyStartDate: "2026-04-01",
      policyEndDate: "2027-03-31",
      idv: 1200000,
      compulsoryDeductible: 2000,
      voluntaryDeductible: 0,
      activeAddOns: ["ZERO_DEPRECIATION", "CONSUMABLES"],
      odClaimsThisPolicyYear: 1,
      originalInvoiceValue: 4600000,
      benefitUsage: {
        engineProtectUsed: 0,
        tyreProtectUsed: 0,
        keyReplacementUsed: 0,
        rsaEventsUsed: 0,
      },
    },
    claim: {
      claimNumber: "CLM-BMW-003",
      policyNumber: "AD26ELITE00982",
      lossDate: "2026-08-22",
      accidentDescription: "Vehicle collided with a road divider at the front-right corner.",
      primaryImpactLocation: "front-right",
      injuryInvolved: false,
      thirdPartyInvolved: false,
      policeReportRequired: false,
    },
    vehicle: {
      registration: "MH01AB1234",
      make: "BMW",
      model: "320d",
      variant: "Luxury Line",
      modelYear: 2021,
      engineCC: 1995,
      vehicleAgeYears: 4.75,
      odometerKm: 58900,
    },
    garage: {
      name: "Prestige Motor Works",
      city: "Mumbai",
      networkStatus: "non_network",
    },
    documentsAvailable: {
      workshopEstimate: true,
      accidentNarrative: true,
      vehicleRegistration: true,
      policyConfirmation: true,
      drivingLicence: true,
      damagePhotographs: true,
    },
  },
  structuredClaim: {
    claim: {
      claimNumber: "CLM-BMW-003",
      lossDate: "2026-08-22",
      accidentDescription: "Vehicle collided with a road divider at the front-right corner.",
      primaryImpactLocation: "front-right",
    },
    vehicle: {
      registration: "MH01AB1234",
      make: "BMW",
      model: "320d",
      variant: "Luxury Line",
      modelYear: 2021,
      engineCC: 1995,
      vehicleAgeYears: 4.75,
    },
    garage: {
      name: "Prestige Motor Works",
      city: "Mumbai",
      networkStatus: "non_network",
    },
    estimate: {
      estimateNumber: "PMW-EST-260821-112",
      partsTotal: 312000,
      labourTotal: 48600,
      paintTotal: 28200,
      grandTotal: 458784,
    },
    lineItems: [
      {
        id: "L1",
        rawDescription: "Front bumper assembly",
        normalizedDescription: "Front bumper assembly",
        quantity: 1,
        partCost: 92000,
        labourCost: 6500,
        totalCost: 98500,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T3-R2-C1", "P1-T3-R2-C4"],
        confidence: "high",
      },
      {
        id: "L2",
        rawDescription: "RH LED headlamp assembly",
        normalizedDescription: "Right-hand LED headlamp assembly",
        quantity: 1,
        partCost: 78000,
        labourCost: 3500,
        totalCost: 81500,
        category: "part",
        material: "electrical",
        action: "replace",
        vehicleLocation: "front right",
        sourceBlockIds: ["P1-T3-R3-C1"],
        confidence: "high",
      },
      {
        id: "L3",
        rawDescription: "RH front fender",
        normalizedDescription: "Right-hand front fender",
        quantity: 1,
        partCost: 48000,
        labourCost: 5000,
        paintCost: 8500,
        totalCost: 61500,
        category: "part",
        material: "metal",
        action: "replace",
        vehicleLocation: "front right",
        sourceBlockIds: ["P1-T3-R4-C1", "P1-T3-R4-C3"],
        confidence: "high",
      },
      {
        id: "L4",
        rawDescription: "Front grille set",
        normalizedDescription: "Front grille set",
        quantity: 1,
        partCost: 19500,
        labourCost: 1200,
        totalCost: 20700,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front grille",
        sourceBlockIds: ["P1-T3-R5-C1", "P1-T3-R5-C2"],
        confidence: "high",
      },
      {
        id: "L5",
        rawDescription: "Front bumper reinforcement",
        normalizedDescription: "Front bumper reinforcement",
        quantity: 1,
        partCost: 16500,
        labourCost: 2500,
        totalCost: 19000,
        category: "part",
        material: "metal",
        action: "replace",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T3-R6-C1"],
        confidence: "high",
      },
      {
        id: "L6",
        rawDescription: "RH wheel arch liner",
        normalizedDescription: "Right-hand wheel arch liner",
        quantity: 1,
        partCost: 6800,
        labourCost: 900,
        totalCost: 7700,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front right wheel arch",
        sourceBlockIds: ["P1-T3-R7-C1", "P1-T3-R7-C2"],
        confidence: "high",
      },
      {
        id: "L7",
        rawDescription: "Undertray / splash shield",
        normalizedDescription: "Undertray and splash shield",
        quantity: 1,
        partCost: 5200,
        labourCost: 800,
        totalCost: 6000,
        category: "part",
        material: "plastic",
        action: "replace",
        vehicleLocation: "front",
        sourceBlockIds: ["P1-T3-R8-C1"],
        confidence: "high",
      },
      {
        id: "L8",
        rawDescription: "Diagnostic scan & coding",
        normalizedDescription: "Diagnostic scan and coding",
        quantity: 1,
        labourCost: 9500,
        totalCost: 9500,
        category: "labour",
        material: "electrical",
        action: "inspect",
        vehicleLocation: "front",
        sourceBlockIds: ["P1-T3-R9-C1"],
        confidence: "high",
      },
      {
        id: "L9",
        rawDescription: "Wheel alignment & suspension check",
        normalizedDescription: "Wheel alignment and suspension check",
        quantity: 1,
        labourCost: 3500,
        totalCost: 3500,
        category: "labour",
        material: "mechanical",
        action: "inspect",
        vehicleLocation: "front axle",
        sourceBlockIds: ["P1-T3-R10-C1"],
        confidence: "high",
      },
      {
        id: "L10",
        rawDescription: "Front bumper painting",
        normalizedDescription: "Front bumper painting",
        quantity: 1,
        labourCost: 2500,
        paintCost: 10500,
        totalCost: 13000,
        category: "paint",
        material: "paint",
        action: "paint",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T3-R11-C1"],
        confidence: "high",
      },
      {
        id: "L11",
        rawDescription: "RH fender painting",
        normalizedDescription: "Right-hand fender painting",
        quantity: 1,
        labourCost: 2200,
        paintCost: 9200,
        totalCost: 11400,
        category: "paint",
        material: "paint",
        action: "paint",
        vehicleLocation: "front right fender",
        sourceBlockIds: ["P1-T3-R12-C1", "P1-T3-R12-C3"],
        confidence: "high",
      },
      {
        id: "L12",
        rawDescription: "Rear LH tail lamp assembly",
        normalizedDescription: "Rear left tail lamp assembly",
        quantity: 1,
        partCost: 38500,
        labourCost: 2500,
        totalCost: 41000,
        category: "part",
        material: "electrical",
        action: "replace",
        vehicleLocation: "rear left",
        sourceBlockIds: ["P1-T3-R13-C1"],
        confidence: "high",
      },
      {
        id: "L13",
        rawDescription: "Front bumper removal & refitting",
        normalizedDescription: "Front bumper removal and refitting",
        quantity: 1,
        labourCost: 9500,
        totalCost: 9500,
        category: "labour",
        material: "unknown",
        action: "repair",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T3-R14-C1"],
        confidence: "high",
      },
      {
        id: "L14",
        rawDescription: "Front bumper dismantling & installation",
        normalizedDescription: "Front bumper dismantling and installation",
        quantity: 1,
        labourCost: 8500,
        totalCost: 8500,
        category: "labour",
        material: "unknown",
        action: "repair",
        vehicleLocation: "front bumper",
        sourceBlockIds: ["P1-T3-R15-C1"],
        confidence: "high",
      },
      {
        id: "L15",
        rawDescription: "Premium consumables / clips / sealants",
        normalizedDescription: "Premium consumables, clips and sealants",
        quantity: 1,
        partCost: 7500,
        totalCost: 7500,
        category: "other",
        material: "unknown",
        action: "unknown",
        sourceBlockIds: ["P1-T3-R16-C1"],
        confidence: "high",
      },
      {
        id: "L16",
        rawDescription: "Tax @18%",
        normalizedDescription: "GST at 18%",
        quantity: 1,
        totalCost: 69984,
        category: "other",
        material: "unknown",
        action: "unknown",
        sourceBlockIds: ["P1-SUMMARY-TAX"],
        confidence: "high",
      },
    ],
    missingInformation: [],
  },
  semanticReview: [
    { itemId: "L1", normalizedDescription: "Front bumper assembly", classification: "CONSISTENT", reason: "Front bumper damage is consistent with the documented front-right collision." },
    { itemId: "L2", normalizedDescription: "Right-hand LED headlamp assembly", classification: "CONSISTENT", reason: "The right headlamp is at the stated impact location." },
    { itemId: "L3", normalizedDescription: "Right-hand front fender", classification: "CONSISTENT", reason: "The right front fender is at the stated impact location." },
    { itemId: "L4", normalizedDescription: "Front grille set", classification: "CONSISTENT", reason: "The grille is within the front impact zone." },
    { itemId: "L5", normalizedDescription: "Front bumper reinforcement", classification: "CONSISTENT", reason: "The reinforcement is consistent with a material front impact." },
    { itemId: "L6", normalizedDescription: "Right-hand wheel arch liner", classification: "CONSISTENT", reason: "The right wheel-arch liner is adjacent to the stated impact." },
    { itemId: "L7", normalizedDescription: "Undertray and splash shield", classification: "CONSISTENT", reason: "The undertray is plausible for a front-corner impact." },
    { itemId: "L8", normalizedDescription: "Diagnostic scan and coding", classification: "POSSIBLY_CONSISTENT", reason: "Diagnostic coding is plausible after headlamp replacement but requires workshop evidence." },
    { itemId: "L9", normalizedDescription: "Wheel alignment and suspension check", classification: "CONSISTENT", reason: "Alignment and suspension checks are plausible after a front-corner impact." },
    { itemId: "L10", normalizedDescription: "Front bumper painting", classification: "CONSISTENT", reason: "Painting follows bumper replacement." },
    { itemId: "L11", normalizedDescription: "Right-hand fender painting", classification: "CONSISTENT", reason: "Painting follows fender replacement." },
    { itemId: "L12", normalizedDescription: "Rear left tail lamp assembly", classification: "INCONSISTENT_WITH_DESCRIPTION", reason: "Rear-left tail-lamp replacement does not correspond with the documented front-right impact." },
    { itemId: "L13", normalizedDescription: "Front bumper removal and refitting", classification: "REQUIRES_VERIFICATION", reason: "Removal/refitting labour may overlap with labour already included in the bumper assembly line." },
    { itemId: "L14", normalizedDescription: "Front bumper dismantling and installation", classification: "REQUIRES_VERIFICATION", reason: "Dismantling/installation appears to overlap with bumper removal and replacement labour." },
    { itemId: "L15", normalizedDescription: "Premium consumables, clips and sealants", classification: "CONSISTENT", reason: "Consumables are plausible for the quoted repair operations." },
    { itemId: "L16", normalizedDescription: "GST at 18%", classification: "CONSISTENT", reason: "The tax line matches the declared subtotal, although line-item arithmetic requires reconciliation." },
  ],
};

export const demoClaims: DemoClaim[] = [cretaClaim, hondaCityClaim, bmwClaim];

export function getDemoClaim(claimId: string): DemoClaim | undefined {
  return demoClaims.find((c) => c.claimId === claimId);
}
